name: Check C++ headers
description: Checks that every C++ file in the repository has valid C++ headers

inputs:
  paths:
    description: |
      The path where source files are located. This could be either a directory,
      a file, or a glob, or a list thereof. If ommitted, defaults to "." (i.e. scan the
      entire repository).
    required: false
    default: '.'
  ignore:
    description: |
      The path(s) that will be ignored by the tool. These could be either individual
      files, or directories, or glob patterns.
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.6.1
      with:
        python-version: '3.10'

    - name: Run check_headers script
      shell: bash
      run: |
        python3 ${{ github.action_path }}/check_headers.py \
          ${{ inputs.paths }} \
          --ignore "${{ inputs.ignore }}"
