name: Run

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-self:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.10

      - name: Run Python Script
        shell: bash
        run: python3 check_headers.py .
